[build]
publish = "docs/public"
command = "hugo -c docs"

[context.production.environment]
HUGO_VERSION = "0.40.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
HUGO_CONTENT_DIR = "docs"
HUGO_OUT = "docs/public"

[context.split1]
command = "hugo --enableGitInfo"

[context.split1.environment]
HUGO_VERSION = "0.40.1"
HUGO_ENV = "production"

[context.production]
publish = "docs/public/"
  


[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.40.1"

[context.branch-deploy]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
HUGO_VERSION = "0.40.1"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

