version: 2.0

defaults: &defaults
  working_directory: ~/sphinx

jobs:
  "check index":
    docker:
      - image: testthedocs/ttd-check
    <<: *defaults
    steps:
      - checkout
      - run:
          command: |
              .circleci/check_index.sh

  "html":
    docker:
      - image: testthedocs/ttd-sphinx
    <<: *defaults
    steps:
      - checkout
      - run: cd docs && make html

      - persist_to_workspace:
          root: ~/sphinx/docs
          paths:
            - _build/html

  "toctree":
    docker:
      - image: testthedocs/ttd-toctree
    <<: *defaults
    steps:
      - checkout
      - run:
           command: |
              cd docs && /usr/local/bin/testtoctree.sh

  "trailing space":
    docker:
      - image: testthedocs/ttd-ts
    <<: *defaults
    steps:
      - checkout
      - run:
           command: |
              cd docs && /usr/local/bin/testts.sh

  "deploy site":
    docker:
      - image: testthedocs/ttd-zipcurl
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: ~/sphinx/html
      - run:
          command: |
              pwd
              ls -la /root
              ls -la ~/sphinx
              .circleci/deploy.sh



workflows:
  version: 2
  btd:
    jobs:
      - "check index"
      - "toctree":
          requires:
             - "check index"
      - "trailing space":
          requires:
             - "toctree"
      - "html":
          requires:
             - "trailing space"
      - "deploy site":
          requires:
             - "html"
